### ISSUE TITLE
[Bug] Server crash when breaking a tripwire in Ancient Vault with Apprentice.

### ISSUE THREAD

**Issue by KnightCa** [WinDanesz/ArcaneApprentices#22] opened 2024-06-12 06:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

I had just removed the Arcane Wall in a Ancient Vault using a Vault key. My Apprentice was following just behind me. When I used a sword to break the tripwire inside, the server crashed.

### Expected behaviour

I expected to access Ancient Vaults without crashing with a Apprentice.

### Steps to reproduce

1. Join a Server
2. Gain a Apprentice
3. With Apprentice following, remove a Arcane Wall in a Ancient Vault
4. Use a sword to break the tripwire.

### Crashlog

https://gist.github.com/KnightCa/2618445de8cd8c30e7581c2ae7fcbf8c

### Environment (Singleplayer/Server, etc.)

Issue present on both sides

### Mod version

1.2.2

### Forge version

1.12.2-forge-14.23.5.2860

**Comment by WinDanesz** [comment] 2024-06-16 13:24
This was caused by dispensers. fixed in 5c614cdec41881447d03f581d311229804d62f4c

**Closed as completed by WinDanesz** 2024-06-16 13:24 UTC
Labels: bug
